export enum RouterMap {
  // phone模块 - 基础页面
  INDEX_PAGE = 'IndexPage',
  SAFE_PAGE = 'SafePage',
  PRIVACY_PAGE = 'PrivacyPage',
  AGREE_PRIVACY_PAGE = 'AgreePrivacyPage',
  START_PAGE = 'StartPage',

  // 首页模块
  HOME_PAGE = 'HomePage',

  // 课程模块
  COURSE_PAGE = 'CoursePage',
  COURSE_DETAIL_PAGE = 'CourseDetailPage',

  // 计划模块
  PLAN_PAGE = 'PlanPage',

  // 我的模块
  MINE_PAGE = 'MinePage',
  MINE_MARK_PAGE = 'MarkPage',
  MINE_HISTORY_PAGE = 'HistoryPage',
  FEEDBACK_PAGE = 'FeedbackPage',

  // 账号模块
  HUAWEI_LOGIN_PAGE = 'HuaweiLoginPage',
  OTHER_LOGIN_PAGE = 'OtherLoginPage',
  PROTOCOL_WEBVIEW = 'ProtocolWebView',

  // 设置模块
  SETTING_PAGE = 'SettingPage',
  SETTING_PERSONAL = 'SettingPersonal',
  SETTING_PRIVACY = 'SettingPrivacy',
  SETTING_ABOUT = 'SettingAbout',

  // 图片预览
  IMAGE_PREVIEW = 'ImagePreview',

  // 反馈模块
  FEEDBACK_RECORD_LIST_PAGE = 'RecordListPage',
  FEEDBACK_SUBMIT_PAGE = 'SubmitPage',
}